### Create BTC Price Alert
POST http://localhost:3000/api/v1/alerts
Content-Type: application/json

{
  "user_id": "89ae8025-b96b-4e15-b931-ddcabc6b0804",
  "symbol": "BTC-USD",
  "target_price": 63000,
  "condition": "ABOVE"
}