### Create BTC Price Alert
POST http://localhost:3000/api/v1/alerts
Content-Type: application/json

{
  "user_id": "0e462ae6-5d5b-49b4-ab39-6787510ac4d5",
  "symbol": "BTC-USD",
  "target_price": 70000,
  "condition": "ABOVE"
}